[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "ag-ui-adk>=0.6.0",
    "ag-ui-langgraph>=0.0.34",
    "copilotkit>=0.1.87",
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "google-adk>=1.31.1",
    "langchain-deepseek>=1.0.1",
    "langchain-openai>=1.1.7",
    "litellm>=1.83.14",
    "uvicorn>=0.46.0",
]
